"""
The Archivist Agent: Living Context Maintainer.

Responsibilities:
- Generate CODEBASE.md (living context file for AI agent injection)
- Generate onboarding_brief.md (Day-One brief with five FDE answers)
- Write cartography_trace.jsonl (audit log of every analysis action)
"""
from __future__ import annotations
import json
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional

from src.graph.knowledge_graph import KnowledgeGraph
from src.models.nodes import Language


class Archivist:
    """
    Agent 4: The Archivist.
    Produces and maintains the system's output artifacts.
    """

    def __init__(
        self,
        kg: KnowledgeGraph,
        repo_path: Path,
        output_dir: Path,
        verbose: bool = True,
    ):
        self.kg = kg
        self.repo_path = repo_path
        self.output_dir = output_dir
        self.verbose = verbose
        self._trace_entries: List[Dict[str, Any]] = []

    def _log(self, msg: str) -> None:
        if self.verbose:
            print(f"  [archivist] {msg}")

    def _trace(
        self,
        action: str,
        evidence_source: str,
        result: str,
        confidence: str = "high",
        method: str = "static_analysis",
    ) -> None:
        """Record an audit trace entry."""
        self._trace_entries.append({
            "timestamp": datetime.utcnow().isoformat(),
            "action": action,
            "evidence_source": evidence_source,
            "result": result,
            "confidence": confidence,
            "method": method,
        })

    # ── CODEBASE.md ───────────────────────────────────────────────────────────

    def generate_codebase_md(
        self,
        day_one_answers: Optional[Dict[str, str]] = None,
        domain_map: Optional[Dict[str, str]] = None,
    ) -> str:
        """
        Generate the living context file for AI agent injection.
        Structured to give an AI coding agent instant architectural awareness.
        """
        lines = []
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        stats = self.kg.stats()

        lines.append("# CODEBASE.md — Brownfield Cartographer Living Context")
        lines.append(f"\n> Auto-generated by Brownfield Cartographer on {now}")
        lines.append(f"> Repository: `{self.repo_path}`")
        lines.append("")

        # ── Architecture Overview ─────────────────────────────────────────────
        lines.append("## Architecture Overview")
        lines.append("")

        # Count languages
        lang_counts: Dict[str, int] = {}
        for mod in self.kg.modules.values():
            # Handle Pydantic V2 enum values being returned as strings directly
            lang = getattr(mod.language, "value", mod.language)
            if not isinstance(lang, str):
                lang = str(lang)
            lang_counts[lang] = lang_counts.get(lang, 0) + 1

        lang_summary = ", ".join(
            f"{count} {lang}" for lang, count in sorted(
                lang_counts.items(), key=lambda x: x[1], reverse=True
            )
        )
        lines.append(
            f"This codebase contains {stats['modules']} modules ({lang_summary}), "
            f"{stats['datasets']} datasets, and {stats['transformations']} data transformations. "
            f"The import graph has {stats['module_edges']} edges with {stats['circular_deps']} circular dependencies."
        )
        lines.append("")

        # Domain breakdown
        if domain_map:
            domains: Dict[str, List[str]] = {}
            for path, domain in domain_map.items():
                domains.setdefault(domain, []).append(path)
            lines.append("**Domain Architecture:**")
            for domain, paths in sorted(domains.items()):
                lines.append(f"- `{domain}` ({len(paths)} files): {', '.join(f'`{p}`' for p in paths[:3])}")
            lines.append("")

        # ── Critical Path ─────────────────────────────────────────────────────
        lines.append("## Critical Path (Top Modules by PageRank)")
        lines.append("")
        lines.append("These are the most imported/depended-upon modules. "
                     "Changes here have the highest blast radius.")
        lines.append("")

        hubs = self.kg.get_critical_path_modules(10)
        for path, score in hubs:
            mod = self.kg.modules.get(path)
            in_deg = self.kg.module_graph.in_degree(path)
            purpose = mod.purpose_statement[:80] if mod and mod.purpose_statement else "no purpose statement"
            lines.append(f"- `{path}` (PageRank={score:.4f}, imported_by={in_deg})")
            lines.append(f"  - {purpose}")

        self._trace(
            "critical_path_extracted",
            "module_graph.pagerank",
            f"Top module: {hubs[0][0] if hubs else 'none'}",
            confidence="high",
            method="static_analysis",
        )
        lines.append("")

        # ── Data Sources and Sinks ────────────────────────────────────────────
        lines.append("## Data Sources & Sinks")
        lines.append("")

        sources = self.kg.find_lineage_sources()
        sinks = self.kg.find_lineage_sinks()

        lines.append("**Data Sources (ingestion points):**")
        for s in sorted(sources)[:15]:
            lines.append(f"- `{s}`")
        lines.append("")

        lines.append("**Data Sinks (output datasets):**")
        for s in sorted(sinks)[:15]:
            lines.append(f"- `{s}`")
        lines.append("")

        self._trace(
            "lineage_sources_sinks_extracted",
            "lineage_graph",
            f"{len(sources)} sources, {len(sinks)} sinks",
            confidence="high",
            method="static_analysis",
        )

        # ── Known Debt ────────────────────────────────────────────────────────
        lines.append("## Known Debt")
        lines.append("")

        circulars = self.kg.find_circular_deps()
        if circulars:
            lines.append("**Circular Dependencies:**")
            for cycle in circulars:
                lines.append(f"- {' <-> '.join(cycle)}")
        else:
            lines.append("**Circular Dependencies:** None detected.")
        lines.append("")

        # Doc drift
        drift_modules = [
            path for path, mod in self.kg.modules.items()
            if mod.doc_drift_flag
        ]
        if drift_modules:
            lines.append("**Documentation Drift (docstring contradicts code):**")
            for path in drift_modules:
                lines.append(f"- `{path}`")
        else:
            lines.append("**Documentation Drift:** None detected.")
        lines.append("")

        # ── High Velocity Files ───────────────────────────────────────────────
        lines.append("## High-Velocity Files (likely pain points)")
        lines.append("")
        lines.append("Files changing most frequently in the last 30 days:")
        lines.append("")

        velocity_files = sorted(
            [(path, mod.change_velocity_30d) for path, mod in self.kg.modules.items()],
            key=lambda x: x[1],
            reverse=True,
        )
        high_velocity = [(p, v) for p, v in velocity_files if v > 0]

        if high_velocity:
            for path, velocity in high_velocity[:10]:
                lines.append(f"- `{path}` — {velocity} commits in 30d")
        else:
            lines.append("- No recent git activity detected.")
        lines.append("")

        # ── Module Purpose Index ──────────────────────────────────────────────
        lines.append("## Module Purpose Index")
        lines.append("")
        lines.append("| File | Language | Domain | Purpose |")
        lines.append("|------|----------|--------|---------|")

        for path, mod in sorted(self.kg.modules.items()):
            purpose = mod.purpose_statement[:60] if mod.purpose_statement else "—"
            domain = mod.domain_cluster or "—"
            lang = getattr(mod.language, "value", mod.language)
            if not isinstance(lang, str):
                lang = str(lang)
            lines.append(f"| `{path}` | {lang} | {domain} | {purpose} |")
        lines.append("")

        # ── Day-One Answers ───────────────────────────────────────────────────
        if day_one_answers and "error" not in day_one_answers:
            lines.append("## FDE Day-One Answers")
            lines.append("")
            question_labels = {
                "q1": "Primary Data Ingestion Path",
                "q2": "Most Critical Output Datasets",
                "q3": "Blast Radius of Critical Module Failure",
                "q4": "Business Logic: Concentrated vs Distributed",
                "q5": "High-Velocity Files (Git Activity)",
            }
            for key, label in question_labels.items():
                answer = day_one_answers.get(key, "Not answered.")
                lines.append(f"### {label}")
                lines.append(answer)
                lines.append("")

            self._trace(
                "day_one_questions_answered",
                "semanticist.synthesis",
                f"All 5 questions answered",
                confidence="medium",
                method="llm_inference",
            )

        return "\n".join(lines)

    # ── onboarding_brief.md ───────────────────────────────────────────────────

    def generate_onboarding_brief(
        self,
        day_one_answers: Optional[Dict[str, str]] = None,
    ) -> str:
        """
        Generate the FDE Day-One onboarding brief.
        A structured document answering the five critical questions.
        """
        lines = []
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        stats = self.kg.stats()

        lines.append("# FDE Day-One Onboarding Brief")
        lines.append(f"\n**Repository:** `{self.repo_path}`")
        lines.append(f"**Generated:** {now}")
        lines.append(f"**Analysis:** {stats['modules']} modules, "
                     f"{stats['datasets']} datasets, "
                     f"{stats['transformations']} transformations")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")

        # Build a brief executive summary from the stats
        sources = self.kg.find_lineage_sources()
        sinks = self.kg.find_lineage_sinks()
        hubs = self.kg.get_critical_path_modules(3)

        lines.append(
            f"This codebase is a data pipeline with {stats['modules']} files, "
            f"{len(sources)} data sources, and {len(sinks)} output datasets. "
            f"The most critical module is `{hubs[0][0] if hubs else 'unknown'}` "
            f"(highest PageRank). "
            f"There are {stats['circular_deps']} circular dependencies."
        )
        lines.append("")
        lines.append("---")
        lines.append("")

        # ── Five Questions ────────────────────────────────────────────────────
        if day_one_answers and "error" not in day_one_answers:
            questions = [
                ("Q1: What is the primary data ingestion path?", "q1"),
                ("Q2: What are the 3-5 most critical output datasets?", "q2"),
                ("Q3: What is the blast radius if the critical module fails?", "q3"),
                ("Q4: Where is business logic concentrated vs distributed?", "q4"),
                ("Q5: What has changed most frequently in the last 90 days?", "q5"),
            ]
            for label, key in questions:
                lines.append(f"## {label}")
                lines.append("")
                answer = day_one_answers.get(key, "Not answered.")
                lines.append(answer)
                lines.append("")
                lines.append("---")
                lines.append("")
        else:
            lines.append("*Semantic analysis not available. "
                         "Run with Semanticist agent for full answers.*")
            lines.append("")

        # ── Quick Reference ───────────────────────────────────────────────────
        lines.append("## Quick Reference")
        lines.append("")
        lines.append("**Data Sources:**")
        for s in sorted(sources)[:10]:
            lines.append(f"- `{s}`")
        lines.append("")
        lines.append("**Data Sinks:**")
        for s in sorted(sinks)[:10]:
            lines.append(f"- `{s}`")
        lines.append("")
        lines.append("**Top Hub Modules:**")
        for path, score in hubs:
            lines.append(f"- `{path}` (PageRank={score:.4f})")
        lines.append("")

        return "\n".join(lines)

    # ── cartography_trace.jsonl ───────────────────────────────────────────────

    def write_trace(self) -> None:
        """Write the audit trace log."""
        trace_path = self.output_dir / "cartography_trace.jsonl"
        with open(trace_path, "w", encoding="utf-8") as f:
            for entry in self._trace_entries:
                f.write(json.dumps(entry) + "\n")
        self._log(f"Trace log written: {len(self._trace_entries)} entries")

    # ── Main Run ──────────────────────────────────────────────────────────────

    def run(
        self,
        day_one_answers: Optional[Dict[str, str]] = None,
        domain_map: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        """Generate all output artifacts."""
        start = time.time()
        self._log("Generating output artifacts...")
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # CODEBASE.md
        self._log("Writing CODEBASE.md...")
        codebase_md = self.generate_codebase_md(day_one_answers, domain_map)
        (self.output_dir / "CODEBASE.md").write_text(
            codebase_md, encoding="utf-8"
        )
        self._trace(
            "codebase_md_generated",
            "all_agents",
            f"{len(codebase_md)} chars written",
            confidence="high",
            method="static_analysis",
        )

        # onboarding_brief.md
        self._log("Writing onboarding_brief.md...")
        brief_md = self.generate_onboarding_brief(day_one_answers)
        (self.output_dir / "onboarding_brief.md").write_text(
            brief_md, encoding="utf-8"
        )
        self._trace(
            "onboarding_brief_generated",
            "all_agents",
            f"{len(brief_md)} chars written",
            confidence="high",
            method="static_analysis",
        )

        # cartography_trace.jsonl
        self.write_trace()

        elapsed = time.time() - start
        self._log(f"Done in {elapsed:.1f}s")
        self._log(f"Output: {self.output_dir}/")

        return {
            "elapsed_seconds": round(elapsed, 2),
            "artifacts": [
                str(self.output_dir / "CODEBASE.md"),
                str(self.output_dir / "onboarding_brief.md"),
                str(self.output_dir / "cartography_trace.jsonl"),
            ],
        }